FROM python:3.10-slim

WORKDIR /app 

# Declare arguments for environment variables
ARG OPENAI_API_KEY
ARG SECRET_KEY
ARG ALGORITHM
ARG ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES
ARG ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS
ARG ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES
ARG ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS
ARG DATABASE_URL_ADDRESS
ARG sqlalchemy_url
ARG EMAIL_ADDRESS
ARG EMAIL_PASSWORD
ARG OTP_EXPIRE
ARG REFRESH_TOKEN_SECRET_KEY
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG PINECONE_API_KEY
ARG PINECONE_API_ENV
ARG PINECONE_API_INDEX
ARG AZURE_STORAGE_CONNECTION_STRING

# Set environment variables
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV SECRET_KEY=$SECRET_KEY
ENV ALGORITHM=$ALGORITHM
ENV ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES=$ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES
ENV ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS=$ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS
ENV ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES=$ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES
ENV ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS=$ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS
ENV DATABASE_URL_ADDRESS=$DATABASE_URL_ADDRESS
ENV sqlalchemy.url=$sqlalchemy_url
ENV EMAIL_ADDRESS=$EMAIL_ADDRESS
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV OTP_EXPIRE=$OTP_EXPIRE
ENV REFRESH_TOKEN_SECRET_KEY=$REFRESH_TOKEN_SECRET_KEY
ENV CLIENT_ID=$CLIENT_ID
ENV CLIENT_SECRET=$CLIENT_SECRET
ENV PINECONE_API_KEY=$PINECONE_API_KEY
ENV PINECONE_API_ENV=$PINECONE_API_ENV
ENV PINECONE_API_INDEX=$PINECONE_API_INDEX
ENV AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING

COPY . .

# Update and install libgl
RUN apt-get clean
RUN apt-get update  

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
