name: Docker Image CI

on:
  push:
    branches: [ "test-script" ]
  pull_request:
    branches: [ "test-script" ]

permissions:
      id-token: write
      contents: read
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v3

    #- name: Login to Azure
      #uses: Azure/login@v2.0.0
      #run: |
        #az login -u abhishek@samisen.io -p MicrosoftAzure26842580#
      #with: 
        #client-id: a384ad8b-1975-4ecf-be7b-9295af9b1ead
        #client_secret: e3aafe1e-5335-4e40-99cf-05a77d28e943
        #tenant-id: 3f699e49-baba-42b2-9990-887b23ed895d
        #subscription-id: 9a1facf0-c31b-44a2-a3cd-11bfaa85f05d 

    #- name: Azure login
      #uses: azure/login@v2
     # with:
        #client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     #   enable-AzPSSession: true

   # - name: Azure CLI script
    #  uses: azure/CLI@v1
     # with:
      #  azcliversion: latest
      #  inlineScript: |
       #   az account show
      #with:
        #creds: '{"clientId": "a384ad8b-1975-4ecf-be7b-9295af9b1ead", "clientSecret": "e3aafe1e-5335-4e40-99cf-05a77d28e943", "subscriptionId": "9a1facf0-c31b-44a2-a3cd-11bfaa85f05d", "tenantId": "3f699e49-baba-42b2-9990-887b23ed895d"}'    
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'   

    #- name: Azure login
      #uses: azure/login@v1
      #with:
        #creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'   
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.registry }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    
    - uses: actions/checkout@v3   
    - name: Build the Docker image
      run: docker build -t eventonaut-data-api-image .  
 
    - name: Create tag
      run: |
        docker tag eventonaut-data-api-image ${{ secrets.registry }}/eventonaut-data-api-image:main-build-${{ github.run_number }}-pr-${{ github.event.pull_request.number }}

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.registry }}/eventonaut-data-api-image:main-build-${{ github.run_number }}-pr-${{ github.event.pull_request.number }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eventonaut-test-main'
        images: ${{ secrets.registry }}/eventonaut-data-api-image:main-build-${{ github.run_number }}-pr-${{ github.event.pull_request.number }}
        #slot-name: <SLOT_NAME>  # Optional, if deploying to a specific deployment slot
  
  #  - name: Deploy to Azure App Service
  #    uses: azure/webapps-deploy@v2
  #    with:
    #    app-name: 'eventonaut-test-main'
     #   slot-name: 'production'
     #   publish-profile: ${{ secrets.TEST_ENV_PUBLISH_PROFILE }}
      #  images: 'eventonaut.azurecr.io/eventonaut-data-api-image:main-build-${{ github.run_number }}-pr-${{ github.event.pull_request.number }}'

    #- name: Restart Azure App Service
    #  run: |
   #     az webapp restart --name eventonaut-test-main --resource-group eventonaut-dev-group 
