name: Docker Image CI

on:
  push:
    branches: [ "test-script" ]
  pull_request:
    branches: [ "test-script" ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALGORITHM: ${{ secrets.ALGORITHM }}
  ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES }}
  ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS: ${{ secrets.ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS }}
  ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES: ${{ secrets.ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES }}
  ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS: ${{ secrets.ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS }}
  DATABASE_URL_ADDRESS: ${{ secrets.DATABASE_URL_ADDRESS }}
  sqlalchemy.url: ${{ secrets.SQLALCHEMY_URL }}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  OTP_EXPIRE: ${{ secrets.OTP_EXPIRE }}
  REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_API_ENV: ${{ secrets.PINECONE_API_ENV }}
  PINECONE_API_INDEX: ${{ secrets.PINECONE_API_INDEX }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.registry }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}

    - name: Build the Docker image
      run: |
        docker build \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
          --build-arg ALGORITHM=${{ secrets.ALGORITHM }} \
          --build-arg ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ORGANIZER_ACCESS_TOKEN_EXPIRE_MINUTES }} \
          --build-arg ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS=${{ secrets.ATTENDEE_ACCESS_TOKEN_EXPIRE_DAYS }} \
          --build-arg ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES=${{ secrets.ORGANIZER_REFRESH_TOKEN_EXPIRE_MINUTES }} \
          --build-arg ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS=${{ secrets.ATTENDEE_REFRESH_TOKEN_EXPIRE_DAYS }} \
          --build-arg DATABASE_URL_ADDRESS=${{ secrets.DATABASE_URL_ADDRESS }} \
          --build-arg sqlalchemy.url=${{ secrets.SQLALCHEMY_URL }} \
          --build-arg EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} \
          --build-arg EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
          --build-arg OTP_EXPIRE=${{ secrets.OTP_EXPIRE }} \
          --build-arg REFRESH_TOKEN_SECRET_KEY=${{ secrets.REFRESH_TOKEN_SECRET_KEY }} \
          --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
          --build-arg CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
          --build-arg PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
          --build-arg PINECONE_API_ENV=${{ secrets.PINECONE_API_ENV }} \
          --build-arg PINECONE_API_INDEX=${{ secrets.PINECONE_API_INDEX }} \
          --build-arg AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
          -t eventonaut-data-api-image .
    
    - name: Tag Docker image
      run: |
        docker tag eventonaut-data-api-image:latest ${{ secrets.registry }}/eventonaut-data-api-image:pr-${{ github.event.pull_request.number }}
    
    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.registry }}/eventonaut-data-api-image:pr-${{ github.event.pull_request.number }}
